### ISSUE TITLE
Formula to calculate item score

### ISSUE THREAD

**Issue by MathieuCesbron** [MathieuCesbron/unidoublev2#1]
Every item should have a score. This score will be used to to show the items to the user with the highest score.

variables available:
1. item_buyer_count (number of people who bought this item)
2. item_rating_count (number of people who rated this item)
3. item_rating (average rating of this item from 0 to 5)
4. sales_volume (in usdc cents, sales volume of the seller)
5. sales_count ( number of people who bought an item from this seller)

objective: Get a formula that accurately score an item with all these parameters. Rewarding seller that sells a lot and punishing sellers with bad ratings.

The score should be a positive number.

**Comment by AntoineMath** [comment]
I would suggest to use the **bayesian rating** since it take into account the number of ratings. 


Here is a [great article](https://www.evanmiller.org/ranking-items-with-star-ratings.html) applying bayesian method to a 5 stars ranking problem.

Do you think we can have the number of each stars for an item ? 

References:
<https://fulmicoton.com/posts/bayesian_rating/>
<https://en.wikipedia.org/wiki/Bayesian_average>

**Comment by MathieuCesbron** [comment]
Looks good ! However we don't have the number of each stars, only the average.

This solution could be implemented once we store the number of each stars which is not gonna happen soon but we might use it in the future.

There must be a simple solution that we can add to the code right now without updating the smart contracts.

**Comment by MathieuCesbron** [comment]
It looks like the bayesian average is simpler and works: https://en.wikipedia.org/wiki/Bayesian_average.
 With ```C=3.5``` and ```m=100```, the scores are decent.
